from setuptools import setup, find_packages

setup(
    name="aclimate_v3_cut_spatial_data",
    version='v0.0.6',
    author="santiago123x",
    author_email="s.calderon@cgiar.com",
    description="Package to clip spatial data (raster/vector) using shapefiles or coordinates. Perfect for processing climate, agricultural, or environmental data",
    url="https://github.com/CIAT-DAPA/aclimate_v3_cut_spatial_data",
    download_url="https://github.com/CIAT-DAPA/aclimate_v3_cut_spatial_data",
    packages=find_packages('src'),
    package_dir={'': 'src'},
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
    install_requires=[
        "affine==2.4.0",
        "attrs==25.3.0",
        "certifi==2025.4.26",
        "charset-normalizer==3.4.2",
        "click==8.2.0",
        "click-plugins==1.1.1",
        "cligj==0.7.2",
        "colorama==0.4.6",
        "dotenv==0.9.9",
        "geopandas==1.0.1",
        "greenlet==3.2.2",
        "idna==3.10",
        "numpy==2.2.6",
        "packaging==25.0",
        "pandas==2.2.3",
        "psycopg2==2.9.10",
        "pyogrio==0.11.0",
        "pyparsing==3.2.3",
        "pyproj==3.7.1",
        "python-dateutil==2.9.0.post0",
        "python-dotenv==1.1.0",
        "pytz==2025.2",
        "rasterio==1.4.3",
        "requests==2.32.3",
        "rioxarray==0.19.0",
        "shapely==2.1.1",
        "six==1.17.0",
        "SQLAlchemy==2.0.41",
        "typing_extensions==4.13.2",
        "tzdata==2025.2",
        "urllib3==2.4.0",
        "xarray==2025.4.0",
        "tomli==2.2.1",
        "exceptiongroup==1.3.0",
        "iniconfig==2.1.0",
        "pluggy==1.6.0",
        "pytest==8.3.5",
    ]
)